server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: fmowinconf
  jpa:
    database-platform: com.fmowinconf.db.dialect.SQLiteDialect
    show-sql: false
  datasource:
    # Cambiamos la ruta a la ra√≠z del proyecto (fuera de src)
    url: jdbc:sqlite:./test.db
    driver-class-name: org.sqlite.JDBC
  devtools:
    restart:
      exclude: "**/*.db,**/test.db"